name: Test build

on:
  push:
    branches: [ "mistress" ]
  pull_request:
    branches: [ "mistress" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]  # Test both compilers

    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake liblua5.4-dev libffi-dev ninja-build libobjc-13-dev gobjc gobjc++ gnustep gnustep-devel libgnustep-base-dev

        # Install clang if needed
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt install -y clang
        fi

    # Configure CMake
    - name: Configure CMake
      run: |
        source /usr/share/GNUstep/Makefiles/GNUstep.sh
        cmake -B build_${{ matrix.compiler }} -S . -G Ninja \
              -DCMAKE_C_COMPILER=/usr/bin/${{ matrix.compiler }} \
              -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.compiler }}++ \
              -DCMAKE_OBJC_COMPILER=/usr/bin/${{ matrix.compiler }} \
              -DCMAKE_OBJCXX_COMPILER=/usr/bin/${{ matrix.compiler }} \
              -DCMAKE_OBJC_FLAGS="-I/usr/include/GNUstep" \
              -DCMAKE_OBJCXX_FLAGS="-I/usr/include/GNUstep" \
              -DCMAKE_EXE_LINKER_FLAGS="-L/usr/lib/GNUstep"


    # Build the project
    - name: Build
      run: |
        source /usr/share/GNUstep/Makefiles/GNUstep.sh
        cmake --build build_${{ matrix.compiler }}
