name: Test build

on:
  push:
    branches: [ "mistress" ]
  pull_request:
    branches: [ "mistress" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]  # Test both compilers

    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake liblua5.4-dev libffi-dev ninja-build libobjc-13-dev gnustep gnustep-devel libgnustep-base-dev

        if [[ "${{ matrix.compiler}}" = "gcc" ]]; then
          sudo apt install -y gobjc gobjc++
        fi

        # Install clang if needed
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt install -y clang
          
          # build and install libobjc2 (required for clang :c)
          git clone https://github.com/gnustep/libobjc2.git
          cd libobjc2
          cmake -B build -S . -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++
          sudo cmake --build build
          sudo cmake --install build
        fi

    # Configure CMake
    - name: Configure CMake
      run: |
        source /usr/share/GNUstep/Makefiles/GNUstep.sh
        if [[ "${{ matrix.compiler }}" == "gcc" ]]; then
          CXX_COMPILER="g++"
          OBJC_COMPILER="gcc"
          OBJCXX_COMPILER="g++"
        else
          CXX_COMPILER="clang++"
          OBJC_COMPILER="clang"
          OBJCXX_COMPILER="clang++"
        fi
        
        cmake -B build_${{ matrix.compiler }} -S . -G Ninja \
              -DCMAKE_C_COMPILER=/usr/bin/${{ matrix.compiler }} \
              -DCMAKE_CXX_COMPILER=/usr/bin/$CXX_COMPILER \
              -DCMAKE_OBJC_COMPILER=/usr/bin/$OBJC_COMPILER \
              -DCMAKE_OBJCXX_COMPILER=/usr/bin/$OBJCXX_COMPILER \
              -DCMAKE_OBJC_FLAGS="$GNUMAKEFLAGS -I/usr/include/GNUstep -I/usr/include/objc/ -I/usr/include/ -I/usr/local/include/GNUstep/objc/ -I/usr/local/include/ -I/usr/local/include/GNUstep" \
              -DCMAKE_OBJCXX_FLAGS="$GNUMAKEFLAGS -I/usr/include/GNUstep -I/usr/include/objc/ -I/usr/include/ -I/usr/local/include/GNUstep/objc/ -I/usr/local/include/ -I/usr/local/include/GNUstep/" \
              -DCMAKE_EXE_LINKER_FLAGS="-L$GNUSTEP_SYSTEM_ROOT/lib -L/usr/lib/GNUstep"




    # Build the project
    - name: Build
      run: |
        source /usr/share/GNUstep/Makefiles/GNUstep.sh
        cmake --build build_${{ matrix.compiler }}
